Signup and login pages
ababber/fun-kickoff-project pull request #1
Opened 2021-11-09 07:17 UTC by ababber

### What this PR does (required):
- changed the style for the login page and the sign up page to align with the mock ups, added the appropriate page links for login and sign up

### Screenshots / Videos (front-end only):
https://user-images.githubusercontent.com/18492009/140877325-08b0ac3a-64c5-4828-b31d-6753b621cb60.mov

### Any information needed to test this feature (required):
- launch the app in your local environment, which will take tester to login page; to navigate to the sign up page use the 'Create an account' link or 'Sign up' button, which will take tester to the sign up page; tester can navigate back to login page by clicking the 'Login' link or 'Login' button

### Any issues with the current functionality (optional):
- the 'Become A Sitter' link navigates tester to login page because the appropriate page has not been created yet

2021-11-09 19:15 UTC, ezeilo-su requested changes
UI looks good. Just address those comments below.

2021-11-09 19:15 UTC, ezeilo-su commented on client/src/pages/Login/LoginForm/LoginForm.tsx
> +          <FormLabel className={classes.formLabel}>EMAIL ADDRESS</FormLabel>
Please avoid using CAPITALCASE for text, some screen readers interpret this text as abbreviations, you can resort to using a CSS class to transform text instead.

2021-11-09 19:15 UTC, ezeilo-su commented on client/src/pages/Login/LoginForm/LoginForm.tsx
> +          <FormLabel className={classes.formLabel}>PASSWORD</FormLabel>
The same thing here as above with CAPITALCASE

2021-11-09 19:15 UTC, ezeilo-su commented on client/src/pages/SignUp/SignUpForm/SignUpForm.tsx
> +          <FormLabel className={classes.formLabel}>EMAIL ADDRESS</FormLabel>
Avoid the use of CAPITALCASE for text. Use CSS to transform, instead.

2021-11-09 19:15 UTC, ezeilo-su commented on client/src/pages/SignUp/SignUpForm/SignUpForm.tsx
> +              {isSubmitting ? <CircularProgress style={{ color: 'white' }} /> : 'SIGN UP'}
CAPITALCASE with text again. Please change it :smile:

2021-11-09 19:26 UTC, rajivtitus commented on client/src/themes/theme.ts
> +    primary: { main: '#F14140' },
💯

2021-11-10 03:52 UTC, ababber commented on client/src/pages/Login/LoginForm/LoginForm.tsx
> +          <FormLabel className={classes.formLabel}>EMAIL ADDRESS</FormLabel>
Thanks for the feedback! I made changes based on your suggestion.

2021-11-10 14:47 UTC, rajivtitus reviewed
A couple of comments weren't posted from the initial review, adding them once again for you to have a look. Thanks! 😄

2021-11-11 02:19 UTC, ababber commented on client/src/components/AuthHeader/AuthHeader.tsx
> +                <Link to="/login" className={classes.link}>
Thanks for the suggestion! That definitely makes the code more concise.

2021-11-11 06:01 UTC, ababber commented on client/src/components/AuthHeader/useStyles.ts
> +    backgroundColor: '#F14140',
Thanks for pointing this out! The color was part of the theme, but I forgot to clean up the useStyles file.

2021-11-11 18:07 UTC, rajivtitus approved these changes
LGTM! Great work implementing those changes! 💯

2021-11-11 18:46 UTC, merged