Tests for logout controller
ababber/fun-kickoff-project pull request #2
Opened 2021-11-10 03:05 UTC by ababber

### What this PR does (required):
- added logout controller tests and updated README with how to run back-end tests

### Any information needed to test this feature (required):
- go into the server directory `cd server`
- ensure your local .env file is setup correctly
- open the package.json file in the server directory
- in the package.json file, add your local .env file to the test script: "DOTENV_CONFIG_PATH=`your_local.env` mocha -r dotenv/config ./test/*.test.js"
- run `npm run test` to start the tests while in the server directory
- if the environment is setup correctly, the test for the logout controller will pass

2021-11-10 14:53 UTC, ugur-akin requested changes
LGTM! Please have a look at the concern about HTTP verbs 👍🏼

2021-11-10 14:53 UTC, ugur-akin commented on server/test/logout.test.js
> +    .get(`/auth/logout`)
`GET` isn't the verb that makes the most sense for a `/logout` path! (see [this article](https://www.baeldung.com/logout-get-vs-post) for more details on why)

The existing implementation may have thrown you off but this is the pitfall of developers building tests - we have to be careful not to biased by our knowledge of the implementation and focus on specs!

2021-11-10 14:55 UTC, ugur-akin approved these changes

2021-11-10 15:23 UTC, rajivtitus approved these changes
LGTM! Just have a look at Ugur's comment :)

2021-11-11 00:46 UTC, ababber commented on server/test/logout.test.js
> +    .get(`/auth/logout`)
Thanks for sharing that article! Web accelerators causing users to logout if the logout link is exposed as a get request is indeed undesirable behavior. I certainly made the test with the implementation in mind instead of spec, I'll keep your advice in mind moving forward :)

2021-11-11 01:17 UTC, merged